name: Waka Readme

on:
  schedule:
    # Runs at 12am KST
    - cron: '30 9 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
#           WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: 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
